Support for editing config file (to an extent) via web dashboard
OCEAN-xyz/datum_gateway pull request #49
Opened 2024-12-13 23:02 UTC by luke-jr

Built on top of #25

Mostly functional, two FIXMEs remain that should have minimal issues until followup. Would be nice to avoid restarting ever, but that can be a future improvement.

2024-12-14 06:00 UTC, wizkid057 commented
tACK

2024-12-14 06:00 UTC, wizkid057 approved these changes
tACK

2024-12-14 06:41 UTC, wizkid057 requested changes
Sorry, missed this when reviewing... GBT cURL call has an aggressive timeout so that the block template thread never hangs.

Booting all stratum clients after a single failure is probably too aggressive, considering the 1 second retry already in play.  Any number of benign things can prevent this call from returning, especially if the node isn't on the same machine.

If we are working on something valid, I'd suggest not booting stratum clients until GBT fails for long enough for the the current job to be stale.

2024-12-16 20:55 UTC, szarka commented
Is there anything in this patch, or elsewhere, that adds access control for the dashboard? AFAIK, that has to be done external to datum_gateway itself right now, but it's not too much of a threat to just display the stats. Adding config editing changes that.

2024-12-17 04:38 UTC, luke-jr commented
@szarka This feature is disabled by default and needs to be turned on with a new config file setting.

Currently, it does not have any special access control, and that could be a possible follow-up PR.

Note that it intentionally does not "read back" the RPC password, only allows changing it.

2024-12-17 13:54 UTC, szarka commented
> @szarka This feature is disabled by default and needs to be turned on with a new config file setting.

Nice. 👍

2025-01-03 17:54 UTC, BitcoinMechanic commented
Let's add authentication to this. Should require (or least give the user the option of requiring) username/password to log in to the dashboard.

2025-01-15 04:37 UTC, luke-jr commented
Not sure authentication is realistic: right now, the webserver is entirely unencrypted and can just be MITM'd...

2025-03-08 06:14 UTC, luke-jr commented
Rebased

* Now requires authentication (encryption left as an exercise for a wrapper)
* Updates new `bitcoind_rpcuserpass` cache when user/password change

2025-03-10 15:30 UTC, wizkid057 approved these changes
tACK

Some notes:
Pooled vs Non-Pooled is a little confusing here in the web configurator vs the config file help doc.  The web configurator always puts the default pool host in the form field, regardless of pooled/non-pooled, but doesn't actually save it to the DATUM pool host if non-pooled is selected... which isn't exactly what I'd expect from that.  Maybe if non-pooled is selected, the pool host form field should be disabled, when possible (probably via JS).

We may want to refactor this someday to better use info from datum_conf a bit more automagically vs the heavily manual list of variables that can be used with this. Including sufficient data in the configuration item structure to accomplish validation and whatnot, along with human descriptions, etc might be the way to go for this one day.

2025-03-10 18:03 UTC, merged